[versions]
# integrations
agp = "8.5.2"
hiddenapibypass = "4.3"
truetypeparser = "2.1.4"
androidx-documentfile = "1.0.1"
androidx-annotation = "1.8.2"
androidx-appcompat = "1.7.0"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.2"
protobuf = "4.27.3"
kotlinx-serialization = "1.7.1"
fastjson = "1.2.83"
# patches
revanced-patcher = "19.3.1"
smali = "3.0.3"
gson = "2.11.0"
kotlin = "2.0.10"
ksp = "2.0.10-1.0.24"
kotlinpoet-ksp = "1.18.1"

[libraries]
gradle-plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# integrations
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
truetypeparser = { module = "io.github.yubyf:truetypeparser-light", version.ref = "truetypeparser" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
protobuf = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet-ksp" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
# patches
revanced-patcher = { module = "kofua.app.revanced:revanced-patcher", version.ref = "revanced-patcher" }
smali = { module = "com.android.tools.smali:smali", version.ref = "smali" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
# integrations
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# patches
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
