blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒ æ–‡æ¡£
    url: https://github.com/revanced/revanced-documentation/
    about: ä¸çŸ¥é“å¦‚ä½•æˆ–ä»å“ªé‡Œå¼€å§‹ï¼ŸæŸ¥çœ‹æˆ‘ä»¬çš„æ–‡æ¡£ï¼
  - name: ğŸ—¨ è®¢é˜…
    url: https://t.me/bb_show
    about: è·å–æœ€æ–°é¢„æ„å»ºå®‰è£…åŒ…ï¼Œè®¢é˜…æ›´æ–°ã€‚
